name: CI - Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Dar permisos de ejecución a Gradle
        run: chmod +x ./gradlew

      - name: Ejecutar tests y generar cobertura
        run: ./gradlew test jacocoTestReport

      - name: Subir reporte de cobertura como artefacto
        uses: actions/upload-artifact@v3.1.3
        with:
          name: coverage-report
          path: build/reports/jacoco/test/html